apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulnerable-workloads
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EQUIPE8/gitops-repo.git
    targetRevision: main
    path: workloads/vulnerable
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
